In [37]:
import posixpath
import numpy as np
import pandas as pd
import geopandas as gpd

In [18]:
data_root = "D:/OneDrive/Documents/Cours/4A/SFE/data/"

kh_fronts = gpd.read_file(posixpath.join(data_root, "KH-5_ARGON_fronts/KH-5_ARGON_fronts.shp")).to_crs(epsg=25833)
landsat_fronts = gpd.read_file(posixpath.join(data_root, "Landsat_MSS_fronts/Landsat_MSS_fronts.shp")).to_crs(epsg=25833)
all_fronts = pd.concat([kh_fronts, landsat_fronts], ignore_index=True)
all_fronts.head()

,image,mission,timestamp,RGI60ID,RGI70ID,front_id,front_dir,geometry
0,DS09058A024MC012,KH-5 ARGON 9058A,1963-08-29,RGI60-07.00777,RGI2000-v7.0-G-07-01225,3,E,"LINESTRING (447461.671 8832029.666, 447497.042..."
1,DS09058A024MC012,KH-5 ARGON 9058A,1963-08-29,RGI60-07.00775,RGI2000-v7.0-G-07-01229,4,SE,"LINESTRING (446131.469 8835920.477, 446232.529..."
2,DS09058A024MC012,KH-5 ARGON 9058A,1963-08-29,RGI60-07.00709,RGI2000-v7.0-G-07-00011,25,W,"LINESTRING (416080.008 8819152.093, 416146.96 ..."
3,DS09058A024MC012,KH-5 ARGON 9058A,1963-08-29,RGI60-07.00664,RGI2000-v7.0-G-07-00015,26,W,"LINESTRING (415736.404 8813938.659, 415733.877..."
4,DS09058A024MC012,KH-5 ARGON 9058A,1963-08-29,RGI60-07.00663,RGI2000-v7.0-G-07-00016,27,W,"LINESTRING (417320.52 8806789.925, 417358.417 ..."

In [50]:
link = pd.DataFrame(
    [],
    columns = ["front_id", "front_dir", "RGI60ID", "RGI70ID"]
)

link.loc[:, "front_id"] = all_fronts.front_id.unique()
link

     front_id front_dir RGI60ID RGI70ID
0           3       NaN     NaN     NaN
1           4       NaN     NaN     NaN
2          25       NaN     NaN     NaN
3          26       NaN     NaN     NaN
4          27       NaN     NaN     NaN
..        ...       ...     ...     ...
176        83       NaN     NaN     NaN
177        84       NaN     NaN     NaN
178        85       NaN     NaN     NaN
179        86       NaN     NaN     NaN
180        88       NaN     NaN     NaN

[181 rows x 4 columns]

In [57]:
link.loc[:, "front_dir"] = link.front_id.apply(lambda i: all_fronts.loc[all_fronts.front_id == i, "front_dir"].values[0])
link.loc[:, "RGI60ID"] = link.front_id.apply(lambda i: all_fronts.loc[all_fronts.front_id == i, "RGI60ID"].values[0])
link.loc[:, "RGI70ID"] = link.front_id.apply(lambda i: all_fronts.loc[all_fronts.front_id == i, "RGI70ID"].values[0])
link.head()

   front_id front_dir         RGI60ID                  RGI70ID
0         3         E  RGI60-07.00777  RGI2000-v7.0-G-07-01225
1         4        SE  RGI60-07.00775  RGI2000-v7.0-G-07-01229
2        25         W  RGI60-07.00709  RGI2000-v7.0-G-07-00011
3        26         W  RGI60-07.00664  RGI2000-v7.0-G-07-00015
4        27         W  RGI60-07.00663  RGI2000-v7.0-G-07-00016

In [42]:
data_root = "D:/OneDrive/Documents/Cours/4A/SFE/data/"

boxes = gpd.read_file(posixpath.join(data_root, "boxes/boxes.shp"), columns=["front_id"]).to_crs(epsg=25833)
boxes.columns = ["front_id_float", 'geometry']
boxes.loc[:, "front_id"] = boxes.front_id_float.astype(int)
boxes = boxes.loc[:, ["front_id", "geometry"]]
boxes

     front_id                                           geometry
0           1  POLYGON ((448958.093 8831407.133, 451132.965 8...
1           2  POLYGON ((448556.464 8831393.624, 447609.196 8...
2           3  POLYGON ((446223.949 8833013.329, 449012.234 8...
3           4  POLYGON ((445849.929 8838239.577, 448611.174 8...
4           5  POLYGON ((444478.132 8842149.605, 443352.455 8...
..        ...                                                ...
170       156  POLYGON ((623706.617 8836555.52, 624719.41 883...
171       157  POLYGON ((621417.761 8836399.539, 621946.741 8...
172       158  POLYGON ((607806.695 8838996.967, 609380.072 8...
173       159  POLYGON ((607952.504 8839437.784, 607452.473 8...
174       160  POLYGON ((616643.376 8820814.971, 619118.732 8...

[175 rows x 2 columns]

In [66]:
boxes.loc[:, "front_dir"] = boxes.front_id.apply(lambda i: link.loc[link.front_id == i].front_dir.values[0])
boxes.loc[:, "RGI60ID"] = boxes.front_id.apply(lambda i: link.loc[link.front_id == i].RGI60ID.values[0])
boxes.loc[:, "RGI70ID"] = boxes.front_id.apply(lambda i: link.loc[link.front_id == i].RGI70ID.values[0])
boxes.loc[:, ["front_id", "RGI60ID", "RGI70ID", "front_dir", "geometry"]]

,front_id,RGI60ID,RGI70ID,front_dir,geometry
0,1,RGI60-07.01494,RGI2000-v7.0-G-07-00054,NE,"POLYGON ((448958.093 8831407.133, 451132.965 8..."
1,2,RGI60-07.00791,RGI2000-v7.0-G-07-01223,NE,"POLYGON ((448556.464 8831393.624, 447609.196 8..."
2,3,RGI60-07.00777,RGI2000-v7.0-G-07-01225,E,"POLYGON ((446223.949 8833013.329, 449012.234 8..."
3,4,RGI60-07.00775,RGI2000-v7.0-G-07-01229,SE,"POLYGON ((445849.929 8838239.577, 448611.174 8..."
4,5,RGI60-07.00794,RGI2000-v7.0-G-07-01268,NE,"POLYGON ((444478.132 8842149.605, 443352.455 8..."
...,...,...,...,...,...
170,156,RGI60-07.00909,RGI2000-v7.0-G-07-01331,NW,"POLYGON ((623706.617 8836555.52, 624719.41 883..."
171,157,RGI60-07.00910,RGI2000-v7.0-G-07-01330,NE,"POLYGON ((621417.761 8836399.539, 621946.741 8..."
172,158,RGI60-07.00067,RGI2000-v7.0-G-07-01327,NE,"POLYGON ((607806.695 8838996.967, 609380.072 8..."
173,159,RGI60-07.00068,RGI2000-v7.0-G-07-01325,NE,"POLYGON ((607952.504 8839437.784, 607452.473 8..."
174,160,RGI60-07.00064,RGI2000-v7.0-G-07-01407,W,"POLYGON ((616643.376 8820814.971, 619118.732 8..."

In [69]:
# /!\ file modification
# boxes.to_file(posixpath.join(data_root, "boxes/boxes.shp"), index=False)