In [22]:
import posixpath
import numpy as np
import pandas as pd
import geopandas as gpd

In [23]:
data_root = "D:/OneDrive/Documents/Cours/4A/SFE/data/"

kh_fronts = gpd.read_file(posixpath.join(data_root, "KH-5_ARGON_fronts/KH-5_ARGON_fronts.shp")).to_crs(epsg=25833)
landsat_fronts = gpd.read_file(posixpath.join(data_root, "Landsat_MSS_fronts/Landsat_MSS_fronts.shp")).to_crs(epsg=25833)
npi_fronts = gpd.read_file(posixpath.join(data_root, "NPI_fronts/NPI_fronts.shp")).to_crs(epsg=25833)
all_fronts = pd.concat([npi_fronts, kh_fronts, landsat_fronts], ignore_index=True)
all_fronts.head()

,mission,timestamp,RGI60ID,RGI70ID,front_id,front_dir,geometry,image
0,NPI 1936-1938 aerial survey,1936-01-01,RGI60-07.00006,RGI2000-v7.0-G-07-00787,77,NW,"LINESTRING (532543.309 8544051.053, 532636.725...",NaN
1,NPI 1936-1938 aerial survey,1936-01-01,RGI60-07.00025,RGI2000-v7.0-G-07-01384,161,S,"LINESTRING (688874.291 8815732.222, 688441.142...",NaN
2,NPI 1936-1938 aerial survey,1936-01-01,RGI60-07.00035,RGI2000-v7.0-G-07-01365,176,E,"LINESTRING (626236.343 8902937.128, 626351.396...",NaN
3,NPI 1936-1938 aerial survey,1936-01-01,RGI60-07.00036,RGI2000-v7.0-G-07-01363,177,E,"LINESTRING (610107.299 8911853.037, 610139.55 ...",NaN
4,NPI 1936-1938 aerial survey,1936-01-01,RGI60-07.01449,RGI2000-v7.0-G-07-01343,144,NW,"LINESTRING (581931.237 8893586.913, 581984.338...",NaN

In [24]:
link = pd.DataFrame(
    [],
    columns = ["front_id", "front_dir", "RGI60ID", "RGI70ID"]
)

link.loc[:, "front_id"] = all_fronts.front_id.unique()
link

     front_id front_dir RGI60ID RGI70ID
0          77       NaN     NaN     NaN
1         161       NaN     NaN     NaN
2         176       NaN     NaN     NaN
3         177       NaN     NaN     NaN
4         144       NaN     NaN     NaN
..        ...       ...     ...     ...
180       167       NaN     NaN     NaN
181       170       NaN     NaN     NaN
182       104       NaN     NaN     NaN
183       102       NaN     NaN     NaN
184        85       NaN     NaN     NaN

[185 rows x 4 columns]

In [25]:
link.loc[:, "front_dir"] = link.front_id.apply(lambda i: all_fronts.loc[all_fronts.front_id == i, "front_dir"].values[0])
link.loc[:, "RGI60ID"] = link.front_id.apply(lambda i: all_fronts.loc[all_fronts.front_id == i, "RGI60ID"].values[0])
link.loc[:, "RGI70ID"] = link.front_id.apply(lambda i: all_fronts.loc[all_fronts.front_id == i, "RGI70ID"].values[0])
link.head()

   front_id front_dir         RGI60ID                  RGI70ID
0        77        NW  RGI60-07.00006  RGI2000-v7.0-G-07-00787
1       161         S  RGI60-07.00025  RGI2000-v7.0-G-07-01384
2       176         E  RGI60-07.00035  RGI2000-v7.0-G-07-01365
3       177         E  RGI60-07.00036  RGI2000-v7.0-G-07-01363
4       144        NW  RGI60-07.01449  RGI2000-v7.0-G-07-01343

In [26]:
centerlines.loc[:, "front_dir"] = centerlines.front_id.apply(lambda i: link.loc[link.front_id == i].front_dir.values[0])
centerlines.loc[:, "RGI60ID"] = centerlines.front_id.apply(lambda i: link.loc[link.front_id == i].RGI60ID.values[0])
centerlines.loc[:, "RGI70ID"] = centerlines.front_id.apply(lambda i: link.loc[link.front_id == i].RGI70ID.values[0])
centerlines.loc[:, ["front_id", "RGI60ID", "RGI70ID", "front_dir", "geometry"]]

,front_id,RGI60ID,RGI70ID,front_dir,geometry
0,73,RGI60-07.00324,RGI2000-v7.0-G-07-01545,S,"LINESTRING (534321.434 8546768.732, 534362.547..."
1,68,RGI60-07.00244,RGI2000-v7.0-G-07-01541,SE,"LINESTRING (521713.665 8552295.499, 521056.825..."
2,61,RGI60-07.00235,RGI2000-v7.0-G-07-00899,NW,"LINESTRING (522358.058 8605537.509, 522635.212..."
3,96,RGI60-07.00422,RGI2000-v7.0-G-07-00916,SE,"LINESTRING (560900.741 8615217.504, 561141.212..."
4,1,RGI60-07.01494,RGI2000-v7.0-G-07-00054,NE,"LINESTRING (449615.704 8824196.706, 449565.438..."
...,...,...,...,...,...
171,174,RGI60-07.00552,RGI2000-v7.0-G-07-01370,N,"LINESTRING (662413.303 8904509.794, 662501.881..."
172,176,RGI60-07.00035,RGI2000-v7.0-G-07-01365,E,"LINESTRING (623057.501 8902129.534, 623270.469..."
173,175,RGI60-07.00035,RGI2000-v7.0-G-07-01365,NW,"LINESTRING (627752.808 8900059.034, 627524.252..."
174,177,RGI60-07.00036,RGI2000-v7.0-G-07-01363,E,"LINESTRING (607756.995 8909417.042, 607773.696..."
175,179,RGI60-07.00049,RGI2000-v7.0-G-07-01351,NW,"LINESTRING (595342.147 8928508.03, 595339.662 ..."

In [28]:
# /!\ file modification
centerlines.to_file(posixpath.join(data_root, "centerlines/centerlines.shp"), index=False)